#!/usr/bin/env bash
#configure nginx to be run by nginx user on should be able to connect to all port 8080

pkill apache2
chmod 777 /etc/nginx/
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 755 /etc/nginx
sudo -u nginx nginx -c /etc/nginx/nginx.conf
